#!/usr/bin/python

import os
import sys
import pyperclip

def alert():
    txt = 'private void alert(String msg, Boolean detach, String btn) {\n'
    txt += 'AlertDialog.Builder x = new AlertDialog.Builder(this);\n'
    txt += 'x.setMessage(msg);\n'
    txt += 'x.setCancelable(detach);\n'
    txt += 'String[] b = btn.split(",,",3);\n'
    txt += 'if (b.length == 3) {\n'
    txt += '    x.setPositiveButton(b[0], null);\n'
    txt += '    x.setNegativeButton(b[1], null);\n'
    txt += '    x.setNeutralButton(b[2],null);\n'
    txt += '} else if (b.length == 2) {\n'
    txt += '    x.setPositiveButton(b[0], null);\n'
    txt += '    x.setNegativeButton(b[1], null);\n'
    txt += '} else {\n'
    txt += '    x.setPositiveButton(b[0], null);\n'
    txt += '}\n'
    txt += 'x.create().show();\n'
    txt += '}\n'
    pyperclip.copy(txt)
    print('Alert Function Copied !')

def colors():
    txt = '<?xml version="1.0" encoding="utf-8"?>\n'
    txt += '<resources>\n'
    txt += '   <color name="colorPrimary">#008577</color>\n'
    txt += '   <color name="colorPrimaryDark">#00574B</color>\n'
    txt += '   <color name="colorAccent">#D81B60</color>\n'
    txt += '   <color name="lightsalmon">#FFA07A</color>\n'
    txt += '   <color name="salmon">#FA8072</color>\n'
    txt += '   <color name="darksalmon">#E9967A</color>\n'
    txt += '   <color name="lightcoral">#F08080</color>\n'
    txt += '   <color name="indianred">#CD5C5C</color>\n'
    txt += '   <color name="crimson">#DC143C</color>\n'
    txt += '   <color name="firebrick">#B22222</color>\n'
    txt += '   <color name="red">#FF0000</color>\n'
    txt += '   <color name="darkred">#8B0000</color>\n'
    txt += '   <color name="coral">#FF7F50</color>\n'
    txt += '   <color name="tomato">#FF6347</color>\n'
    txt += '   <color name="orangered">#FF4500</color>\n'
    txt += '   <color name="gold">#FFD700</color>\n'
    txt += '   <color name="orange">#FFA500</color>\n'
    txt += '   <color name="darkorange">#FF8C00</color>\n'
    txt += '   <color name="lightyellow">#FFFFE0</color>\n'
    txt += '   <color name="lemonchiffon">#FFFACD</color>\n'
    txt += '   <color name="lightgoldenrodyellow">#FAFAD2</color>\n'
    txt += '   <color name="papayawhip">#FFEFD5</color>\n'
    txt += '   <color name="moccasin">#FFE4B5</color>\n'
    txt += '   <color name="peachpuff">#FFDAB9</color>\n'
    txt += '   <color name="palegoldenrod">#EEE8AA</color>\n'
    txt += '   <color name="khaki">#F0E68C</color>\n'
    txt += '   <color name="darkkhaki">#BDB76B</color>\n'
    txt += '   <color name="yellow">#FFFF00</color>\n'
    txt += '   <color name="lawngreen">#7CFC00</color>\n'
    txt += '   <color name="chartreuse">#7FFF00</color>\n'
    txt += '   <color name="limegreen">#32CD32</color>\n'
    txt += '   <color name="lime">#00FF00</color>\n'
    txt += '   <color name="forestgreen">#228B22</color>\n'
    txt += '   <color name="green">#008000</color>\n'
    txt += '   <color name="darkgreen">#006400</color>\n'
    txt += '   <color name="greenyellow">#ADFF2F</color>\n'
    txt += '   <color name="yellowgreen">#9ACD32</color>\n'
    txt += '   <color name="springgreen">#00FF7F</color>\n'
    txt += '   <color name="mediumspringgreen">#00FA9A</color>\n'
    txt += '   <color name="lightgreen">#90EE90</color>\n'
    txt += '   <color name="palegreen">#98FB98</color>\n'
    txt += '   <color name="darkseagreen">#8FBC8F</color>\n'
    txt += '   <color name="mediumseagreen">#3CB371</color>\n'
    txt += '   <color name="seagreen">#2E8B57</color>\n'
    txt += '   <color name="olive">#808000</color>\n'
    txt += '   <color name="darkolivegreen">#556B2F</color>\n'
    txt += '   <color name="olivedrab">#6B8E23</color>\n'
    txt += '   <color name="lightcyan">#E0FFFF</color>\n'
    txt += '   <color name="cyan">#00FFFF</color>\n'
    txt += '   <color name="aqua">#00FFFF</color>\n'
    txt += '   <color name="aquamarine">#7FFFD4</color>\n'
    txt += '   <color name="mediumaquamarine">#66CDAA</color>\n'
    txt += '   <color name="paleturquoise">#AFEEEE</color>\n'
    txt += '   <color name="turquoise">#40E0D0</color>\n'
    txt += '   <color name="mediumturquoise">#48D1CC</color>\n'
    txt += '   <color name="darkturquoise">#00CED1</color>\n'
    txt += '   <color name="lightseagreen">#20B2AA</color>\n'
    txt += '   <color name="cadetblue">#5F9EA0</color>\n'
    txt += '   <color name="darkcyan">#008B8B</color>\n'
    txt += '   <color name="teal">#008080</color>\n'
    txt += '   <color name="powderblue">#B0E0E6</color>\n'
    txt += '   <color name="lightblue">#ADD8E6</color>\n'
    txt += '   <color name="lightskyblue">#87CEFA</color>\n'
    txt += '   <color name="skyblue">#87CEEB</color>\n'
    txt += '   <color name="deepskyblue">#00BFFF</color>\n'
    txt += '   <color name="lightsteelblue">#B0C4DE</color>\n'
    txt += '   <color name="dodgerblue">#1E90FF</color>\n'
    txt += '   <color name="cornflowerblue">#6495ED</color>\n'
    txt += '   <color name="steelblue">#4682B4</color>\n'
    txt += '   <color name="royalblue">#4169E1</color>\n'
    txt += '   <color name="blue">#0000FF</color>\n'
    txt += '   <color name="mediumblue">#0000CD</color>\n'
    txt += '   <color name="darkblue">#00008B</color>\n'
    txt += '   <color name="navy">#000080</color>\n'
    txt += '   <color name="midnightblue">#191970</color>\n'
    txt += '   <color name="mediumslateblue">#7B68EE</color>\n'
    txt += '   <color name="slateblue">#6A5ACD</color>\n'
    txt += '   <color name="darkslateblue">#483D8B</color>\n'
    txt += '   <color name="lavender">#E6E6FA</color>\n'
    txt += '   <color name="thistle">#D8BFD8</color>\n'
    txt += '   <color name="plum">#DDA0DD</color>\n'
    txt += '   <color name="violet">#EE82EE</color>\n'
    txt += '   <color name="orchid">#DA70D6</color>\n'
    txt += '   <color name="fuchsia">#FF00FF</color>\n'
    txt += '   <color name="magenta">#FF00FF</color>\n'
    txt += '   <color name="mediumorchid">#BA55D3</color>\n'
    txt += '   <color name="mediumpurple">#9370DB</color>\n'
    txt += '   <color name="blueviolet">#8A2BE2</color>\n'
    txt += '   <color name="darkviolet">#9400D3</color>\n'
    txt += '   <color name="darkorchid">#9932CC</color>\n'
    txt += '   <color name="darkmagenta">#8B008B</color>\n'
    txt += '   <color name="purple">#800080</color>\n'
    txt += '   <color name="indigo">#4B0082</color>\n'
    txt += '   <color name="pink">#FFC0CB</color>\n'
    txt += '   <color name="lightpink">#FFB6C1</color>\n'
    txt += '   <color name="hotpink">#FF69B4</color>\n'
    txt += '   <color name="deeppink">#FF1493</color>\n'
    txt += '   <color name="palevioletred">#DB7093</color>\n'
    txt += '   <color name="mediumvioletred">#C71585</color>\n'
    txt += '   <color name="white">#FFFFFF</color>\n'
    txt += '   <color name="snow">#FFFAFA</color>\n'
    txt += '   <color name="honeydew">#F0FFF0</color>\n'
    txt += '   <color name="mintcream">#F5FFFA</color>\n'
    txt += '   <color name="azure">#F0FFFF</color>\n'
    txt += '   <color name="aliceblue">#F0F8FF</color>\n'
    txt += '   <color name="ghostwhite">#F8F8FF</color>\n'
    txt += '   <color name="whitesmoke">#F5F5F5</color>\n'
    txt += '   <color name="seashell">#FFF5EE</color>\n'
    txt += '   <color name="beige">#F5F5DC</color>\n'
    txt += '   <color name="oldlace">#FDF5E6</color>\n'
    txt += '   <color name="floralwhite">#FFFAF0</color>\n'
    txt += '   <color name="ivory">#FFFFF0</color>\n'
    txt += '   <color name="antiquewhite">#FAEBD7</color>\n'
    txt += '   <color name="linen">#FAF0E6</color>\n'
    txt += '   <color name="lavenderblush">#FFF0F5</color>\n'
    txt += '   <color name="mistyrose">#FFE4E1</color>\n'
    txt += '   <color name="gainsboro">#DCDCDC</color>\n'
    txt += '   <color name="lightgray">#D3D3D3</color>\n'
    txt += '   <color name="silver">#C0C0C0</color>\n'
    txt += '   <color name="darkgray">#A9A9A9</color>\n'
    txt += '   <color name="gray">#808080</color>\n'
    txt += '   <color name="dimgray">#696969</color>\n'
    txt += '   <color name="lightslategray">#778899</color>\n'
    txt += '   <color name="slategray">#708090</color>\n'
    txt += '   <color name="darkslategray">#2F4F4F</color>\n'
    txt += '   <color name="black">#000000</color>\n'
    txt += '   <color name="cornsilk">#FFF8DC</color>\n'
    txt += '   <color name="blanchedalmond">#FFEBCD</color>\n'
    txt += '   <color name="bisque">#FFE4C4</color>\n'
    txt += '   <color name="navajowhite">#FFDEAD</color>\n'
    txt += '   <color name="wheat">#F5DEB3</color>\n'
    txt += '   <color name="burlywood">#DEB887</color>\n'
    txt += '   <color name="tan">#D2B48C</color>\n'
    txt += '   <color name="rosybrown">#BC8F8F</color>\n'
    txt += '   <color name="sandybrown">#F4A460</color>\n'
    txt += '   <color name="goldenrod">#DAA520</color>\n'
    txt += '   <color name="peru">#CD853F</color>\n'
    txt += '   <color name="chocolate">#D2691E</color>\n'
    txt += '   <color name="saddlebrown">#8B4513</color>\n'
    txt += '   <color name="sienna">#A0522D</color>\n'
    txt += '   <color name="brown">#A52A2A</color>\n'
    txt += '   <color name="maroon">#800000</color>\n'
    txt += '</resources>\n'
    pyperclip.copy(txt)
    print('Colours Copied !')


def constraint():
    txt = '<?xml version="1.0" encoding="utf-8"?>\n'
    txt += '<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"\n'
    txt += '   xmlns:app="http://schemas.android.com/apk/res-auto"\n'
    txt += '   xmlns:tools="http://schemas.android.com/tools"\n'
    txt += '   android:layout_width="match_parent"\n'
    txt += '   android:layout_height="match_parent">\n\n'
    txt += '</androidx.constraintlayout.widget.ConstraintLayout>'
    pyperclip.copy(txt)
    print('Constraint Layout Copied !')


def tr():
    txt = '<TableRow\n'
    txt += '    android:layout_width="match_parent"\n'
    txt += '    android:layout_height="wrap_content">\n\n'
    txt += '</TableRow>'
    pyperclip.copy(txt)
    print("Table Row Copied !")


def horizontal():
    txt = '<?xml version="1.0" encoding="utf-8"?>\n'
    txt += '<HorizontalScrollView xmlns:android="http://schemas.android.com/apk/res/android"\n'
    txt += '    xmlns:app="http://schemas.android.com/apk/res-auto"\n'
    txt += '    xmlns:tools="http://schemas.android.com/tools"\n'
    txt += '    android:layout_width="match_parent"\n'
    txt += '    android:layout_height="match_parent"\n'
    txt += '    android:fillViewport="true">\n\n'
    txt += '</HorizontalScrollView>'
    pyperclip.copy(txt)
    print("Copied Main Horizontal Scroll View !")


def linear():
    txt = '<?xml version="1.0" encoding="utf-8"?>\n'
    txt += '<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"\n'
    txt += '    xmlns:app="http://schemas.android.com/apk/res-auto"\n'
    txt += '    xmlns:tools="http://schemas.android.com/tools"\n'
    txt += '    android:layout_width="match_parent"\n'
    txt += '    android:layout_height="match_parent"\n'
    txt += '    android:paddingLeft="16dp"\n'
    txt += '    android:paddingRight="16dp"\n'
    txt += '    android:orientation="vertical">\n\n'
    txt += '  <!--  Your Content Here  -->\n\n'
    txt += '</LinearLayout>'
    pyperclip.copy(txt)
    print("Copied Main Linear Layout !")


def relative():
    txt = '<?xml version="1.0" encoding="utf-8"?>\n'
    txt += '<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"\n'
    txt += '    xmlns:app="http://schemas.android.com/apk/res-auto"\n'
    txt += '    xmlns:tools="http://schemas.android.com/tools"\n'
    txt += '    android:layout_width="match_parent"\n'
    txt += '    android:layout_height="match_parent"\n'
    txt += '    android:paddingLeft="16dp"\n'
    txt += '    android:paddingRight="16dp">\n\n'
    txt += '  <!-- Your Content Here  -->\n\n'
    txt += '</RelativeLayout>'
    pyperclip.copy(txt)
    print("Copied Main Relative Layout !")


def scroll():
    txt = '<?xml version="1.0" encoding="utf-8"?>\n'
    txt += '<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"\n'
    txt += '    xmlns:app="http://schemas.android.com/apk/res-auto"\n'
    txt += '    xmlns:tools="http://schemas.android.com/tools"\n'
    txt += '    android:layout_width="match_parent"\n'
    txt += '    android:layout_height="match_parent"\n'
    txt += '    android:fillViewport="true">\n\n'
    txt += '</ScrollView>'
    pyperclip.copy(txt)
    print("Copied Main Scroll View!")


def table():
    txt = '<?xml version="1.0" encoding="utf-8"?>\n'
    txt += '<TableLayout xmlns:android="http://schemas.android.com/apk/res/android"\n'
    txt += '    xmlns:app="http://schemas.android.com/apk/res-auto"\n'
    txt += '    xmlns:tools="http://schemas.android.com/tools"\n'
    txt += '    android:layout_width="match_parent"\n'
    txt += '    android:layout_height="match_parent">\n\n'
    txt += '    <!-- first row of the table layout-->\n'
    txt += '    <TableRow\n'
    txt += '        android:layout_width="match_parent"\n'
    txt += '        android:layout_height="wrap_content">\n\n'
    txt += '    </TableRow>\n\n'
    txt += '</TableLayout>\n'
    pyperclip.copy(txt)
    print("Copied Main Table Layout !")


args = sys.argv[1:]

if len(args) == 0:
    print("l - linear")
    print("r - relative")
    print("t - table")
    print("s - scroll")
    print('h - horizontal')
    print('color - colours')
else:
    arg = args[0].lower()
    if arg == 'color':
        colors()
    elif arg[:1] == 'a':
        alert()
    elif arg[:2] == 'tr':
        tr()
    elif arg[:1] == 'l':
        linear()
    elif arg[:1] == 'r':
        relative()
    elif arg[:1] == 't':
        table()
    elif arg[:1] == 's':
        scroll()
    elif arg[:1] == 'h':
        horizontal()
    elif arg[:1] == 'c':
        constraint()
    else:
        print("l - linear")
        print("r - relative")
        print("t - table")
        print("s - scroll")
        print('h - horizontal')
        print('a - alert')

#
